# **I. Import all the necessary libraries**

In [1]:
from utils import *
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt


# **II. Import and Preprocess the dataset**

In [2]:
data = pd.read_csv('Student_Performance.csv')


In [3]:
train, test = train_test_split(data)


In [4]:
x_test = test[['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced']]
y_test = test['Performance Index']


In [5]:
x_train = train[['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced']]
y_train = train['Performance Index']


In [6]:
data


Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

Columns to normalize: All except for extracurricular activities

In [7]:
features = ['Hours Studied', 'Previous Scores', 'Extracurricular Activities', 'Sleep Hours', 'Sample Question Papers Practiced']


In [8]:
x_meta = [x_test,x_train]


In [9]:
exp = test['Extracurricular Activities']


In [10]:
x_meta = [x_test,x_train]
y_meta = [y_test,y_train]
for i in features:
    for j in x_meta:
        if i == 'Extracurricular Activities':
            dict_map = {
                'Yes' : 1,
                'No' : 0,
            }
            j['Extracurricular Activities'] = j['Extracurricular Activities'].map(dict_map)
        else:
            j[i] = z_score_normalize(j[i])
del x_meta,y_meta


/var/folders/36/khn_y8zn7qqflczfpst8cbfc0000gn/T/ipykernel_97778/1995739649.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  j[i] = z_score_normalize(j[i])
/var/folders/36/khn_y8zn7qqflczfpst8cbfc0000gn/T/ipykernel_97778/1995739649.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  j[i] = z_score_normalize(j[i])
/var/folders/36/khn_y8zn7qqflczfpst8cbfc0000gn/T/ipykernel_97778/1995739649.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[ro

In [11]:
x_train


Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
2824          0.125         0.644068                           0          1.0   
4457          1.000         0.711864                           0          0.2   
678           0.125         0.203390                           0          0.2   
2038          0.000         0.050847                           0          0.8   
6126          0.125         0.813559                           0          0.2   
...             ...              ...                         ...          ...   
7915          0.000         0.237288                           1          0.2   
7178          0.875         0.779661                           0          0.0   
3602          0.750         0.254237                           0          0.6   
8575          0.250         0.406780                           0          1.0   
4856          1.000         0.966102                           0          0.2   

      Sample Question Papers Practiced  
2824                          0.333333  
4457                          0.888889  
678                           0.555556  
2038                          0.666667  
6126                          0.222222  
...                                ...  
7915                          0.444444  
7178                          0.444444  
3602                          0.333333  
8575                          1.000000  
4856                          0.777778  

[7500 rows x 5 columns]

In [12]:
y_train


2824    54.0
4457    80.0
678     26.0
2038    15.0
6126    59.0
        ... 
7915    26.0
7178    79.0
3602    49.0
8575    47.0
4856    95.0
Name: Performance Index, Length: 7500, dtype: float64

# **III. Train the model**

In [13]:
model = LinearRegression()


In [14]:
model.batch_gradient_descent_train(x_train,y_train,epochs=1000)


(1, 5) [[-208811.07209863 -230482.68635928 -190855.59289077 -197184.55883239
  -197746.29167713]]
(1, 5) [[-194735.22887126 -216440.18610538 -176087.84326152 -182881.13188291
  -183399.84489807]]
(1, 5) [[-181640.11166279 -203372.33949331 -162361.31780247 -169577.3685814
  -170056.1796611 ]]
(1, 5) [[-169457.23812215 -191211.09665768 -149603.22853179 -157203.4560623
  -157645.26307917]]
(1, 5) [[-158122.90876432 -179893.16037955 -137745.87158803 -145694.45726401
  -146101.95346015]]
(1, 5) [[-147577.87292548 -169359.65415218 -126726.27214144 -134989.97039313
  -135365.65869586]]
(1, 5) [[-137767.01804852 -159555.81342973 -116485.85410527 -125033.81217241
  -125380.01850997]]
(1, 5) [[-128639.0806695  -150430.69843978 -106970.13291532 -115773.72321128
  -116092.60889837]]
(1, 5) [[-120146.37758945 -141936.92705366  -98128.42976631 -107161.09395397
  -107454.667212  ]]
(1, 5) [[-112244.55582167 -134030.42631366  -89913.60580666  -99150.70976793
   -99420.83644057]]
(1, 5) [[-104892.36000

In [15]:
print(model.w,model.b)


[[21.08065545]
 [55.04874427]
 [ 0.2286725 ]
 [ 1.75491548]
 [ 1.2644674 ]] 15.766330719266337


In [23]:
print(model.predict(x_test.iloc[0].to_numpy()),y_test.iloc[0])


[[85.8864122]] 86.0


In [17]:
data.columns


Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [18]:
print(model.predict(x_test.iloc[4].to_numpy()),y_test.iloc[4])


[[48.3454532]] 46.0


In [19]:
prediction = []
for i in range(x_test.shape[0]):
    prediction.append(model.predict(x_test.iloc[i].to_numpy()))


In [ ]:
prediction


[array([[85.8864122]]),
 array([[32.96177535]]),
 array([[48.79153433]]),
 array([[20.59890962]]),
 array([[48.3454532]]),
 array([[44.22464592]]),
 array([[67.62249041]]),
 array([[68.05660084]]),
 array([[80.6064178]]),
 array([[69.43462992]]),
 array([[86.43910798]]),
 array([[24.23171196]]),
 array([[53.3850945]]),
 array([[41.07748275]]),
 array([[61.27136095]]),
 array([[16.96029208]]),
 array([[62.28019605]]),
 array([[72.20915173]]),
 array([[48.51236858]]),
 array([[78.90143171]]),
 array([[27.38708324]]),
 array([[38.72102576]]),
 array([[89.03594318]]),
 array([[87.37746215]]),
 array([[64.93639748]]),
 array([[61.48714716]]),
 array([[56.9860061]]),
 array([[50.91800956]]),
 array([[57.2806787]]),
 array([[37.99210181]]),
 array([[38.9339054]]),
 array([[83.31254658]]),
 array([[30.38736892]]),
 array([[79.49518593]]),
 array([[35.02607263]]),
 array([[62.20091598]]),
 array([[87.70545056]]),
 array([[73.19954829]]),
 array([[28.41361352]]),
 array([[66.50142801]]),
 array(

In [27]:
y_test


7754    86.0
8359    33.0
9194    46.0
5254    13.0
9468    46.0
        ... 
5383    72.0
5542    24.0
3956    47.0
5399    21.0
3751    69.0
Name: Performance Index, Length: 2500, dtype: float64

In [36]:
calculate_mae(prediction,y_test.to_numpy())


21.47130036812588

The reason why the model performs bad might be that there is there is a feature that is categorical and not numerical. A Linear Regression model is not able to handle this feature very well.